# Generated by Django 4.1.4 on 2022-12-10 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('keywords', models.ImageField(blank=True, max_length=200, upload_to='')),
                ('image', models.ImageField(blank=True, upload_to='images/')),
                ('subject', models.CharField(blank=True, max_length=500)),
                ('detail', models.TextField()),
                ('when', models.TextField()),
                ('status', models.CharField(choices=[('true', 'evet'), ('false', 'hayır')], max_length=10)),
                ('slug', models.SlugField(unique=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activity.category')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='activity.activity')),
            ],
        ),
    ]
