# Generated by Django 4.1.4 on 2022-12-10 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0002_activity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='Category',
            new_name='category',
        ),
    ]
